title = "Ainsley does computer: a blog"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Ainsley McGrath is a software engineer at Amper Technologies who talks a lot."
  copyright = "Copyright © 2020 Ainsley McGrath"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
